package bank.transaction.entity;

public enum TransactionType {
	DEPOSIT,//DEPÓSITO
    WITHDRAWAL,//RETIRADA
    PAYMENT,//PAGO
    TRANSFER,//TRANSFERENCIA
    DEBIT_CARD_PAYMENT,//PAGO CON TARJETA DE DÉBITO
    CREDIT_CARD_PAYMENT,//PAGO CON TARJETA DE CRÉDITO
    CREDIT_PAYMENT //PAGO CON CRÉDITO
}
